#STELLAR_HORIZON = "https://horizon-testnet.stellar.org"
STELLAR_HORIZON =  "https://horizon.stellar.org"
STELLAR_SECRET = "SAA3PTWCCKO6UDTITTDEP5PMD5PTXSIDGAFKJI66X6PNZ454XSHKLOGY"
STELLAR_PUBLIC = "GDAZCZBU3U5LEOQ7BJSMVYFSXC766E6C37QHNGBTID6U4BQS2SBGMFR7"
